# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
  pull_request:

jobs:
  test:

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 14
          - 15
          - 16
          - 17

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ matrix.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci

      - name: Benchmark
        if: github.event_name == 'schedule'
        run: npm run benchmarks

      - name: Upload coverage to Codecov
        if: github.event_name != 'schedule'
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,NODE_VERSION
          fail_ci_if_error: true
